### ISSUE TITLE
Not working out of the box

### ISSUE THREAD

**Issue by Neurobaby** [jizongFox/DeepClusteringProject#12]
Hi,

This looks like an amazing repository but it's not working after downloading.  Went to main.py and tried to run and got:

`C:\Anaconda3\envs\FastAI\python.exe D:/Anon/Documents/PycharmProjects/DeepClusteringProject/main.py
The filename, directory name, or volume label syntax is incorrect.
C:\Anaconda3\envs\FastAI\lib\site-packages\deepclustering\model\convert2apex.py:12: RuntimeWarning: Apex not installed, using PyTorch default setting.
  warnings.warn("Apex not installed, using PyTorch default setting.", RuntimeWarning)
C:\Anaconda3\envs\FastAI\lib\site-packages\sklearn\utils\linear_assignment_.py:22: FutureWarning: The linear_assignment_ module is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)
Checkout MNIST dataset with transforms:
Traceback (most recent call last):
  File "D:/Anon/Documents/PycharmProjects/DeepClusteringProject/main.py", line 161, in <module>
    scheduler_dict=merged_config["Scheduler"],
TypeError: __init__() got an unexpected keyword argument 'arch_dict'

Process finished with exit code 1`

Any ideas please?

I have yet to get any IIC repository to work or get anywhere near 90-95% so I'm really hoping this one will.

Thank you

**Comment by Neurobaby** [comment]
Actually - it failed because I had the deepclustering library installed.  When I uninstalled that and ran from the local library that part went through but then got this:

'C:\Anaconda3\envs\FastAI\python.exe D:/Anon/Documents/PycharmProjects/DeepClusteringProject/main.py
D:\Anon\Documents\PycharmProjects\DeepClusteringProject\library\deep-clustering-toolbox\deepclustering\model\convert2apex.py:12: RuntimeWarning: Apex not installed.
  warnings.warn("Apex not installed.", RuntimeWarning)
C:\Anaconda3\envs\FastAI\lib\site-packages\sklearn\utils\linear_assignment_.py:22: FutureWarning: The linear_assignment_ module is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)
Checkout MNIST dataset with transforms:
Traceback (most recent call last):
  File "D:/Anon/Documents/PycharmProjects/DeepClusteringProject/main.py", line 167, in <module>
    Trainer = get_trainer(merged_config)
  File "D:/Anon/Documents/PycharmProjects/DeepClusteringProject/main.py", line 18, in get_trainer
    assert config.get("Trainer").get("name"), config.get("Trainer").get("name")
AssertionError: None

Process finished with exit code 1'

Fixed this by adding name: iicgeo to the config file.

Then got an Apex not installed warning on every epoch so had to hide that.

Then in assignment mapping kept throwing warning so changed it to FutureWarning:   warnings.simplefilter("ignore", FutureWarning)

Had to change self.entropy._eps to self.entropy.eps in trainer\loss.py

It seems to be working now.  Trained for 10 iterations with no improvement at all past 25% using either scipy linear_sum_assignment or the sklearn linear_assignment.

How many iterations does it usually take before you see the performance improve?

**Comment by cxr12345** [comment]
> 实际上-它失败了，因为我安装了Deepclustering库。当我卸载它并从本地库中运行该部分时，却遇到了这个问题：
> 
> 'C：\ Anaconda3 \ envs \ FastAI \ python.exe D：/Anon/Documents/PycharmProjects/DeepClusteringProject/main.py
> D：\ Anon \ Documents \ PycharmProjects \ DeepClusteringProject \ library \ deep-Clustering-toolbox \ deepclustering \ model \ convert2apex.py:12：RuntimeWarning：未安装Apex。
> warnings.warn（“未安装Apex。”，RuntimeWarning）
> C：\ Anaconda3 \ envs \ FastAI \ lib \ site-packages \ sklearn \ utils \ linear_assignment_.py：22：FutureWarning：linear_assignment_模块已在0.21中弃用，并将在从0.23移除。请改用scipy.optimize.linear_sum_assignment。
> （FutureWarning）
> 签出具有转换的MNIST数据集：追溯
> （最近一次调用为最新）：
> 文件“ D：/Anon/Documents/PycharmProjects/DeepClusteringProject/main.py”，第167行，位于
> 培训师= get_trainer（merged_config）
> 文件“ D：/Anon/Documents/PycharmProjects/DeepClusteringProject/main.py”，第18行，位于get_trainer中
> assert config.get（“ Trainer”）。get（“ name”），config.get（ “ Trainer”）。get（“ name”）
> AssertionError：无
> 
> 流程以退出代码1'完成
> 
> 通过在配置文件中添加名称：iicgeo来解决此问题。
> 
> 然后在每个纪元上都出现未安装Apex的警告，因此必须将其隐藏。
> 
> 然后在分配映射中不断抛出警告，因此将其更改为FutureWarning：warnings.simplefilter（“ ignore”，FutureWarning）
> 
> 必须在Trainer \ loss.py中将self.entropy.eps更改为self.entropy.eps
> 
> 它现在似乎正在工作。使用scipy linear_sum_assignment或sklearn linear_assignment进行了10次迭代的训练，在过去的25％上没有任何改善。
> 
> 在看到性能提高之前，通常需要执行几次迭代？

Hello, I encountered the same problem as you. The others have been modified according to your steps. The only one is: Fixed this by adding name: iicgeo to the config file. What does this sentence mean? Or how should I configure it? thank you very much

**Comment by Alex866850** [comment]
> Actually - it failed because I had the deepclustering library installed. When I uninstalled that and ran from the local library that part went through but then got this:
> 
> 'C:\Anaconda3\envs\FastAI\python.exe D:/Anon/Documents/PycharmProjects/DeepClusteringProject/main.py
> D:\Anon\Documents\PycharmProjects\DeepClusteringProject\library\deep-clustering-toolbox\deepclustering\model\convert2apex.py:12: RuntimeWarning: Apex not installed.
> warnings.warn("Apex not installed.", RuntimeWarning)
> C:\Anaconda3\envs\FastAI\lib\site-packages\sklearn\utils\linear_assignment_.py:22: FutureWarning: The linear_assignment_ module is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
> FutureWarning)
> Checkout MNIST dataset with transforms:
> Traceback (most recent call last):
> File "D:/Anon/Documents/PycharmProjects/DeepClusteringProject/main.py", line 167, in
> Trainer = get_trainer(merged_config)
> File "D:/Anon/Documents/PycharmProjects/DeepClusteringProject/main.py", line 18, in get_trainer
> assert config.get("Trainer").get("name"), config.get("Trainer").get("name")
> AssertionError: None
> 
> Process finished with exit code 1'
> 
> Fixed this by adding name: iicgeo to the config file.
> 
> Then got an Apex not installed warning on every epoch so had to hide that.
> 
> Then in assignment mapping kept throwing warning so changed it to FutureWarning: warnings.simplefilter("ignore", FutureWarning)
> 
> Had to change self.entropy._eps to self.entropy.eps in trainer\loss.py
> 
> It seems to be working now. Trained for 10 iterations with no improvement at all past 25% using either scipy linear_sum_assignment or the sklearn linear_assignment.
> 
> How many iterations does it usually take before you see the performance improve?

Hello, I encountered the same problem as you. The others have been modified according to your steps. The only one is: Fixed this by adding name: iicgeo to the config file. What does this sentence mean? Or how should I configure it? thank you very much
